// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4CdJlThqn2Kfe9I7LOmHWQyc1tMKI2U',
    appId: '1:734975451672:web:492b59d7eefb14616c596d',
    messagingSenderId: '734975451672',
    projectId: 'chathub-3cbbe',
    authDomain: 'chathub-3cbbe.firebaseapp.com',
    storageBucket: 'chathub-3cbbe.appspot.com',
    measurementId: 'G-83TR20NK4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_MDCpth-KxTfTQgheMRGfAn_a6h-A2w',
    appId: '1:734975451672:android:b77fb3e82a5acd856c596d',
    messagingSenderId: '734975451672',
    projectId: 'chathub-3cbbe',
    storageBucket: 'chathub-3cbbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MHlrphKcgJUUEfdowGuFmnZtSdw-csY',
    appId: '1:734975451672:ios:6d28209a52c134a26c596d',
    messagingSenderId: '734975451672',
    projectId: 'chathub-3cbbe',
    storageBucket: 'chathub-3cbbe.appspot.com',
    iosClientId: '734975451672-lf2fdg4qtppb386v4c9klki9na06bqen.apps.googleusercontent.com',
    iosBundleId: 'com.example.litehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6MHlrphKcgJUUEfdowGuFmnZtSdw-csY',
    appId: '1:734975451672:ios:aa62e7669d5a338d6c596d',
    messagingSenderId: '734975451672',
    projectId: 'chathub-3cbbe',
    storageBucket: 'chathub-3cbbe.appspot.com',
    iosClientId: '734975451672-jm1ruqs506ah9dtq5v67es99fhg704e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.litehub.RunnerTests',
  );
}
